# Generated by Django 5.2.7 on 2025-10-17 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pastebin_entry',
            fields=[
                ('date_of_post', models.DateTimeField(verbose_name='creation date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pastebin_entry_title', models.CharField(max_length=100)),
                ('pastebin_entry_string', models.TextField()),
            ],
        ),
    ]
