# Generated by Django 5.2.7 on 2025-10-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pastebin_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('title', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
